# Generated by Django 3.0.3 on 2020-02-11 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_list', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchlist',
            name='query',
        ),
    ]
